// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKAa-W_z8ltIeGy5MJ4vuY02g8bkIzELM',
    appId: '1:375010464684:web:c29a8868903b8195a72009',
    messagingSenderId: '375010464684',
    projectId: 'pushpak-311b1',
    authDomain: 'pushpak-311b1.firebaseapp.com',
    storageBucket: 'pushpak-311b1.firebasestorage.app',
    measurementId: 'G-9Q431T1QDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnBIFvREBO-Ki-WmmZg7mZwE9oN7dRJuA',
    appId: '1:375010464684:android:b27b39acf7eacd67a72009',
    messagingSenderId: '375010464684',
    projectId: 'pushpak-311b1',
    storageBucket: 'pushpak-311b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgZauXUZUY_6VgUWHpoI-PVTP5cwcMVIY',
    appId: '1:375010464684:ios:45c8d6eade89cb78a72009',
    messagingSenderId: '375010464684',
    projectId: 'pushpak-311b1',
    storageBucket: 'pushpak-311b1.firebasestorage.app',
    iosBundleId: 'com.example.pushpak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgZauXUZUY_6VgUWHpoI-PVTP5cwcMVIY',
    appId: '1:375010464684:ios:45c8d6eade89cb78a72009',
    messagingSenderId: '375010464684',
    projectId: 'pushpak-311b1',
    storageBucket: 'pushpak-311b1.firebasestorage.app',
    iosBundleId: 'com.example.pushpak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKAa-W_z8ltIeGy5MJ4vuY02g8bkIzELM',
    appId: '1:375010464684:web:f0d5ff451cee071fa72009',
    messagingSenderId: '375010464684',
    projectId: 'pushpak-311b1',
    authDomain: 'pushpak-311b1.firebaseapp.com',
    storageBucket: 'pushpak-311b1.firebasestorage.app',
    measurementId: 'G-SHC2E91EGJ',
  );
}
